"""Interactive user config setup using free PATH detection, never agent probes."""
from __future__ import annotations

import copy
import shlex
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from .config import ROLES, user_config
from .core import StargateError
from .doctor import AGENT_CLI_WRAPPERS, available_agent_clis


@dataclass(frozen=True)
class Vendor:
    name: str
    description: str
    agents: dict[str, Any]
    reader: str
    writer: str
    binary: str
    reviewer_command: list[str] | None


def load_vendors(script_dir: Path) -> list[Vendor]:
    catalog = yaml.safe_load((script_dir / "vendors.yaml").read_text())
    vendors = []
    for name, entry in catalog["vendors"].items():
        agents = entry["agents"]
        readers = [key for key, block in agents.items() if block["probe_expect"] == "read"]
        writers = [key for key, block in agents.items() if block["probe_expect"] == "write"]
        if len(readers) != 1 or len(writers) != 1:
            raise StargateError(f"Packaged vendor {name} needs one reader and one writer")
        reader, writer = readers[0], writers[0]
        binary = agents[reader]["command"][0]
        reviewer = entry.get("reviewer_command")
        if agents[writer]["command"][0] != binary or (reviewer and reviewer[0] != binary):
            raise StargateError(f"Packaged vendor {name} has inconsistent command executables")
        vendors.append(Vendor(name, entry["description"], agents, reader, writer, binary, reviewer))
    return vendors


def ask(role: str, options: list[Vendor], default: Vendor) -> Vendor:
    capability = "reads your repository" if role in ("architect", "reviewer") else "may edit files"
    print(f"\n{role} — {capability}")
    for number, vendor in enumerate(options, 1):
        print(f"  {number}. {vendor.name}: {vendor.description}")
    while True:
        answer = input(f"{role} [{default.name}]: ").strip().lower()
        if not answer:
            return default
        for number, vendor in enumerate(options, 1):
            if answer in (str(number), vendor.name):
                return vendor
        print("Choose a listed number or vendor name, or press Enter for the default.")


def compose(selection: dict[str, Vendor], version: Any) -> str:
    agents: dict[str, Any] = {}
    workflow = {}
    header = "# Generated by stargate init-config.\n"
    for role, vendor in selection.items():
        name = vendor.reader if role in ("architect", "reviewer") else vendor.writer
        block = copy.deepcopy(vendor.agents[name])
        if role == "reviewer" and vendor.reviewer_command:
            name = f"{vendor.name}_reviewer"
            block["command"] = list(vendor.reviewer_command)
        agents[name] = block
        workflow[role] = name
        header += f"# {role}: {vendor.name} (examples/{vendor.name}/README.md)\n"
    header += (
        "# Settings inherit from the packaged layer. Vendor flag comments and\n"
        "# example-level settings (including Kiro's) are not copied; see the sources above.\n"
    )
    print("\nSelected commands:")
    for role, name in workflow.items():
        print(f"  {role}: {name} — {shlex.join(agents[name]['command'])}")
    return header + yaml.safe_dump(
        {"version": version, "agents": agents, "workflow": workflow}, sort_keys=False,
    )


def init_config(script_dir: Path, *, force: bool = False) -> int:
    target = user_config()
    if target.exists() and not force:
        print(f"Already exists, not overwriting: {target}")
        print("Re-run with --force to replace it (a timestamped backup is kept).")
        return 1

    vendors = load_vendors(script_dir)
    installed = [vendor for vendor in vendors if shutil.which(vendor.binary)]
    other_clis = available_agent_clis({vendor.binary for vendor in vendors})
    found = {name for name, _, _ in other_clis}
    for vendor in vendors:
        underlying = AGENT_CLI_WRAPPERS.get(vendor.binary)
        if vendor not in installed and underlying in found:
            print(f"MISSING {vendor.binary}: {underlying} found, but the "
                  f"examples/{vendor.name} wrapper is not on PATH.")
    if not installed:
        print("No verified agent CLI is available. Missing command executables:")
        for vendor in vendors:
            print(f"  MISSING {vendor.binary} — {vendor.description}")
        print("Writing the packaged default; install its CLIs or re-run setup after installation.")

    content = (script_dir / "agents.yaml").read_text()
    if not sys.stdin.isatty():
        print("stdin is not a terminal; skipping the agent CLI questions. "
              "Copying the packaged default.")
    elif installed:
        packaged = yaml.safe_load(content)
        selection = {}
        ended = False
        try:
            for role in ROLES:
                binary = packaged["agents"][packaged["workflow"][role]]["command"][0]
                default = next((v for v in installed if v.binary == binary), installed[0])
                try:
                    selection[role] = default if ended else ask(role, installed, default)
                except EOFError:
                    print("\nInput ended; remaining roles take their defaults.")
                    ended = True
                    selection[role] = default
        except KeyboardInterrupt:
            print("\nAborted; nothing was written.")
            return 130
        content = compose(selection, packaged["version"])

    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        backup = target.with_name(f"agents.yaml.{datetime.now():%Y%m%d-%H%M%S-%f}.bak")
        shutil.copy2(target, backup)
        print(f"Backed up {backup}")
    # Exclusive creation also prevents a concurrently created config being clobbered.
    with target.open("w" if force else "x") as stream:
        stream.write(content)
    print(f"Wrote {target}")
    print("Settings inherit from the packaged layer; edit this config to override them.")
    if other_clis:
        print("Also detected, not configurable by init-config: " + ", ".join(sorted(found)))
        print("See examples/README.md for writing and verifying other command prefixes.")
    print("Inspect with: stargate doctor")
    print("Verify with: stargate doctor --probe (one real, billable call per distinct agent)")
    return 0
